global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'service-a'
    static_configs:
      - targets: ['172.17.0.1:3000']

  - job_name: 'service-b'
    static_configs:
      - targets: ['172.17.0.1:3001']

  - job_name: 'service-c'
    static_configs:
      - targets: ['172.17.0.1:3002']

